export const GET_GAMELIST_BEGIN = "GET_GAMELIST_BEGIN";
export const GET_GAMELIST_SUCCESS = "GET_GAMELIST_SUCCESS";
export const GET_GAMELIST_FAIL = "GET_GAMELIST_FAIL";

export const GET_GAMEDETAIL_BEGIN = "GET_GAMELIST_BEGIN";
export const GET_GAMEDETAIL_SUCCESS = "GET_GAMEDETAIL_SUCCESS";
export const GET_GAMEDETAIL_FAIL = "GET_GAMEDETAIL_FAIL";

export const GET_BYGENRE_BEGIN = "GET_BYGENRE_BEGIN";
export const GET_BYGENRE_SUCCESS = "GET_BYGENRE_SUCCESS";
export const GET_BYGENRE_FAIL = "GET_BYGENRE_FAIL";

export const GET_SEARCH_BEGIN = "GET_SEARCH_BEGIN";
export const GET_SEARCH_SUCCESS = "GET_SEARCH_SUCCESS";
export const GET_SEARCH_FAIL = "GET_SEARCH_FAIL";

export const CLEAR = "CLEAR"